inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('alumnos/crear/', views.crear_alumno, name='crear_alumno'),
    path('alumnos/lista_alumnos/', views.lista_alumnos, name='lista_alumnos'),
]

tercera_preentrega/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('inicio.urls')),
    path('admin/', admin.site.urls),
]

inicio/models.py
from django.db import models

# Create your models here.

class CrearAlumno(models.Model):
    nombre = models.CharField(max_length=20)
    apellido = models.CharField(max_length=20)
    curso = models.IntegerField()
    division = models.CharField(max_length=1)

inicio/forms.py
from django import forms


class CrearAlumnoForm(forms.Form):
    nombre = forms.CharField(max_length=20)
    apellido = forms.CharField(max_length=20)
    curso = forms.IntegerField()
    division = forms.CharField(max_length=1, )
    
class BuscarAlumnoApellidoForm(forms.Form):
    apellido = forms.CharField(max_length=20, required=False)
    

inicio/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from inicio.forms import CrearAlumnoForm, BuscarAlumnoApellidoForm
from inicio.models import CrearAlumno
# Create your views here.

def inicio(request):
    return render(request, 'inicio/inicio.html')

def crear_alumno(request):
    
    
    if request.method == 'POST':
        formulario = CrearAlumnoForm(request.POST)
        if formulario.is_valid():
            info = formulario.cleaned_data
            alumno = CrearAlumno(nombre=info['nombre'],apellido=info['apellido'], curso=info['curso'], division=info['division'] )
            alumno.save()

            return redirect('inicio:lista_alumnos')
        else:
            return render(request, 'inicio/crear_alumno.html')
            
    formulario = CrearAlumnoForm()
    return render(request, 'inicio/crear_alumno.html', {'formulario': formulario})

def lista_alumnos(request):
    formulario = BuscarAlumnoApellidoForm(request.GET)
    if formulario.is_valid():
        apellido_a_buscar = formulario.cleaned_data['apellido']
        listado_de_alumnos = CrearAlumno.objects.filter(apellido__icontains=apellido_a_buscar)
    
    formulario = BuscarAlumnoApellidoForm()
    return render(request, 'inicio/lista_alumnos.html', {'formulario': formulario, 'alumnos': listado_de_alumnos})

inicio/templates/inicio/crear_alumno.html
{% extends 'base.html' %}
{% load static %}

{% block title_head %}
<title>Inscribir Alumno</title>
{% endblock title_head %}

{% block portada %}
<img class="img-fluid" src={% static 'assets/img/portfolio/portadaprueba.png' %} alt="..." />
{% endblock portada %}

{% block h1_header %}
<h1 class="masthead-heading text-uppercase mb-0">Inscripción de alumno</h1>
{% endblock h1_header %}

{% block subheading %}
{% endblock subheading %}

{% block contenido %}
<p>{{mensaje}}</p>
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Inscribir</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/inicio.html
{% extends 'base.html' %}

{% block title_head %}
<title>Inicio</title>
{% endblock title_head %}

{% block h1_header %}
<h1 class="masthead-heading text-uppercase mb-0">Bienvenidos a mi página</h1>
{% endblock h1_header %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">Tercera pre-entrega CoderHouse</p>
{% endblock subheading %}

{% block contenido %}

{% endblock contenido %}

inicio/templates/inicio/lista_alumnos.html
{% extends 'base.html' %}
{% load static %}

{% block title_head %}
<title>Lista de alumnos</title>
{% endblock title_head %}

{% block portada %}
<img class="img-fluid" src={% static 'assets/img/portfolio/portadaprueba.png' %} alt="..." />
{% endblock portada %}

{% block h1_header %}
<h1 class="masthead-heading text-uppercase mb-0">Listado de alumnos/as</h1>
{% endblock h1_header %}

{% block subheading %}

{% endblock subheading %}


{% block contenido %}
<button>
    <li class="nav-item mx-0 mx-lg-1"><a class="masthead-subheading font-weight-light mb-0" href={% url 'inicio:crear_alumno' %}>Inscribir alumno/a</a></li>
</button>
<form action="" method="get">
    {{formulario}}
    <button>Buscar</button>
</form>

{% if alumnos %}
{% for alumno in alumnos %}
<li>Nombre: {{alumno.nombre}} - Apellido: {{alumno.apellido}} - Curso: {{alumno.curso}} - División {{alumno.division}}</li>
{% endfor %}
{% else %}
<p>No se han encontrado datos.</p>
{% endif %}
{% endblock contenido %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>Freelancer - Start Bootstrap Theme</title>
        {% endblock title_head %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/styles.css' %} rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>
                {% comment %} <a class="navbar-brand" href={% url 'inicio:crear_alumno' %}>Registrar Alumno</a> {% endcomment %}
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        {% block lista_de_alumnos %}
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:lista_alumnos' %}>Alumnos</a></li>
                        {% endblock lista_de_alumnos %}

                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image-->
                {% comment %} <img class="masthead-avatar mb-5" src={% static 'assets/img/avataaars.svg' %} alt="..." /> {% endcomment %}
                {% block portada %}
                <img class="img-fluid" src={% static 'assets/img/portfolio/natanuevo.png' %} alt="..." />
                {% endblock portada %}
                <!-- Masthead Heading-->
                {% block h1_header %}
                <h1 class="masthead-heading text-uppercase mb-0">Start Bootstrap</h1>
                {% endblock h1_header %}
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
                {% block subheading %}
                <p class="masthead-subheading font-weight-light mb-0">Graphic Artist - Web Designer - Illustrator</p>
                {% endblock subheading %}
            </div>
        </header>
        

        {% block contenido %}
        
        {% endblock contenido %}     
        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    
                    <!-- Footer Social Icons-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Around the Web</h4>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-linkedin-in"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-dribbble"></i></a>
                    </div>
                    
                </div>
            </div>
        </footer>
       
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static "js/scripts.js" %}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>